import os
import argparse
import wandb
from datasets import load_dataset
from trl import SFTTrainer, SFTConfig
from unsloth import FastLanguageModel
from unsloth.chat_templates import get_chat_template

def main():
    parser = argparse.ArgumentParser(description="Fine-tune IKS Bharat Persona using Unsloth")
    parser.add_argument("--resume", action="store_true", help="Resume from the latest checkpoint if it crashed")
    args = parser.parse_args()

    # ----------------------------------------------------------------------
    # 1. Weights & Biases Setup
    # ----------------------------------------------------------------------
    wandb.init(project="iks-bharat-persona", name="gemma-3-12b-run-1")

    # ----------------------------------------------------------------------
    # 2. Model & LoRA Configuration
    # ----------------------------------------------------------------------
    max_seq_length = 4096 
    dtype = None # Auto detection
    load_in_4bit = True # Use 4bit quantization to save memory

    print("Loading Base Model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name = "unsloth/gemma-3-12b-it-bnb-4bit",
        max_seq_length = max_seq_length,
        dtype = dtype,
        load_in_4bit = load_in_4bit,
        token = os.environ.get("HF_TOKEN") # Optional: in case gated access needed
    )

    print("Configuring LoRA for deep persona injection...")
    model = FastLanguageModel.get_peft_model(
        model,
        r = 32,             # Higher rank for stylistic/persona changes
        target_modules = ["q_proj", "k_proj", "v_proj", "o_proj",
                          "gate_proj", "up_proj", "down_proj",],
        lora_alpha = 64,    # Alpha = 2 * r is standard
        lora_dropout = 0,   # 0 is optimized for Unsloth
        bias = "none",
        use_gradient_checkpointing = "unsloth", # Crucial for 15k multi-turn examples
        random_state = 3407,
        use_rslora = False,
        loftq_config = None,
    )

    # ----------------------------------------------------------------------
    # 3. Dataset Preparation
    # ----------------------------------------------------------------------
    print("Loading Dataset...")
    tokenizer = get_chat_template(
        tokenizer,
        chat_template = "gemma",
    )

    def formatting_prompts_func(examples):
        convos = examples["conversations"]
        texts = [tokenizer.apply_chat_template(convo, tokenize = False, add_generation_prompt = False) for convo in convos]
        return { "text" : texts, }

    # Load the local JSONL file generated by the World Collector
    dataset = load_dataset("json", data_files="data/curated/iks_instruction_dataset.jsonl", split="train")
    dataset = dataset.map(formatting_prompts_func, batched = True,)

    # ----------------------------------------------------------------------
    # 4. Training Configuration
    # ----------------------------------------------------------------------
    print("Initializing SFTTrainer...")
    trainer = SFTTrainer(
        model = model,
        tokenizer = tokenizer,
        train_dataset = dataset,
        dataset_text_field = "text",
        max_seq_length = max_seq_length,
        dataset_num_proc = 2,
        packing = False,
        args = SFTConfig(
            per_device_train_batch_size = 2,
            gradient_accumulation_steps = 4,
            warmup_steps = 50,
            num_train_epochs = 3,
            learning_rate = 2e-4,
            fp16 = not getattr(model.config, "is_bfloat16_supported", False)(),
            bf16 = getattr(model.config, "is_bfloat16_supported", False)(),
            logging_steps = 10,
            optim = "adamw_8bit",
            weight_decay = 0.01,
            lr_scheduler_type = "linear",
            seed = 3407,
            output_dir = "outputs",
            report_to = "wandb",              # W&B enabled
            gradient_checkpointing = True,    # Avoid OOM on long sequences
            save_strategy = "steps",
            save_steps = 500,                 # Save checkpoint every 500 steps
            save_total_limit = 3,             # Keep only the last 3 checkpoints
        ),
    )

    # ----------------------------------------------------------------------
    # 5. Training
    # ----------------------------------------------------------------------
    print(f"Starting Training! Resume mode: {args.resume}")
    # If resuming, Unsloth/HF Trainer automatically picks up the latest checkpoint in output_dir
    trainer_stats = trainer.train(resume_from_checkpoint=args.resume)

    print("Training Complete. Saving Final Model...")
    # Save the LoRA adapters locally
    model.save_pretrained("iks_bharat_lora")
    tokenizer.save_pretrained("iks_bharat_lora")

    print("Done. To merge and export to GGUF, see Unsloth documentation.")

if __name__ == "__main__":
    main()
